### PR TITLE
Hosted CE updater

### PR DESCRIPTION
**Pull request by matyasselmeci**
Add hosted CE updater script which updates a worker node tarball on a remote node via rsync and SSH

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
The script LGTM. I'm a little confused as to what the plan is for installation, configuration, and running all of this, though. Do we add the tarball-client as a requirement of `osg-ce-bosco`, configure how it's called with `osg-configure`, and have this run as a schedd cron or crondor job?

**Comment by matyasselmeci** [comment]
I assumed this was specific to hosted CEs, not bosco CEs in general; that's why I figured the tarball-client repo would be the best place for it. There's no RPM for the tarball-client (what would that even mean?) so we'd have to make a new RPM for this, like "bosco-ce-scripts" or something.

**Comment by matyasselmeci** [comment]
Can we get Marco to try this out manually on a CE? In particular, I want to make sure the rsync works with a shared file system as the destination.

**Comment by brianhlin** [comment]
I'd be surprised if there are any bosco CEs that aren't hosted CEs since we don't advertise it. I think we should treat them as one and the same. Instead of creating a new RPM, maybe we could drop these two files directly into `osg-ce-bosco` instead (along with any necessary config for the schedd cron or whatever).

Having @mmascher test this out would be a good idea. Could you give him instructions for setting this up and running it?

**Comment by matyasselmeci** [comment]
Let's discuss this off-ticket.

**Comment by brianhlin** [comment]
We discussed this off-ticket and we decided that this belongs in the `htcondor-ce-bosco` OSG packaging so we should move this PR to https://github.com/opensciencegrid/htcondor-ce

**Comment by matyasselmeci** [comment]
Moved to opensciencegrid/hosted-ce-tools.

**Pull request closed without merging**
