### PR TITLE
Build tarballs in travis-ci on changes.

### PR DESCRIPTION
**Pull request by bbockelm**
First stab at travis-ci integration for PR verification.

### CODE REVIEW

**Comment by bbockelm** [comment]
@matyasselmeci - it seems the EL6 failures are real.  Batlab mirror of EPEL6 is broken?

**Comment by bbockelm** [comment]
Ah, actually looks like the `osg-3.2-el6-release-build` repo just needs to be regen'd.  Any objections to doing that?

**Comment by matyasselmeci** [comment]
I did a regen-repo -- which you should feel free to do any time. Is there a way to retry the tests?

**Comment by bbockelm** [comment]
Yeah - I was about 99% sure that `regen-repo` couldn't hurt anything, but wanted to double-check.  I'll hit the retry button.

**Comment by bbockelm** [comment]
Ok, CI is happy after the `regen-repo`.  @matyasselmeci - ready for this to go in?

**Pull request merged**
