### PR TITLE
add osg 3.5 stuff (SOFTWARE-3761) 

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Can you add the repos/osg-3.5.repo.in file as well?

**Comment by matyasselmeci** [comment]
It looks good but let's hold off on merging it until 3.5 repos exist.

**Review by matyasselmeci — APPROVED** [review]

**Comment by brianhlin** [comment]
3.5 repos exist now. Does that mean this is ready to go?

**Comment by matyasselmeci** [comment]
I'll merge this; I'll make a second PR to change the 3.5 repo definitions to pull from development since there isn't anything in 3.5-release.

**Pull request merged**
